spring.application.name=tienda

#para definir el puerto donde estara el servidor
server.port = 80

#Para definierr el formato de despliegue de fehca/hora del log en la consola
logging.pattern.dateformat=hh:mm

#Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

#En desarrollo el "cache" del servidor (false), en produccion "true"
spring.thymeleaf.cache=false
